spring.application.name=modulith-step4-documentation

# Module-level Flyway migrations
spring.modulith.runtime.flyway-enabled=true
spring.sql.init.mode=never

# H2 Console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
